config/routes.rb
Rails.application.routes.draw do
  resources :crowd_inputs

  resources :tps

  get 'profiles/:id', :controller => 'profiles', :action => 'show'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root to: 'pages#home'

end

app/models/crowd_input.rb
class CrowdInput < ActiveRecord::Base
  belongs_to :tps
  belongs_to :user
  validates :prabowo_count, :jokowi_count, :broken_count, inclusion: { in: 0..1000 }

  self.per_page = 10

  def c1_url
    return tps.c1_url
  end
end

app/models/tps.rb
class Tps < ActiveRecord::Base
  def c1_url
    return "http://scanc1.kpu.go.id/viewp.php?f=#{self.kelurahan_id}#{self.tps_id.rjust(3, '0')}04.jpg"
  end

  def self.random_id
    return self.offset(rand(self.count)).first.id
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:facebook]
  validates :name, presence: true

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
      # user.image = auth.info.image
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:name, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/crowd_inputs_controller.rb
class CrowdInputsController < ApplicationController
  before_action :set_crowd_input, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /crowd_inputs
  # GET /crowd_inputs.json
  def index
    @crowd_inputs = CrowdInput.paginate(:page => params[:page])
  end

  # GET /crowd_inputs/new
  def new
    unless current_user.is_banned
      @crowd_input = CrowdInput.new
      @crowd_input.tps_id = Tps.random_id
      @crowd_input.prabowo_count = 0
      @crowd_input.jokowi_count = 0
      @crowd_input.broken_count = 0

      initialize_variables
    else
      render :text => "Anda telah diblokir"
    end
  end

  # POST /crowd_inputs
  # POST /crowd_inputs.json
  def create
    unless current_user.is_banned
      @crowd_input = CrowdInput.new(crowd_input_params)
      @crowd_input.user_id = current_user.id

      respond_to do |format|
        if @crowd_input.save
          format.html { redirect_to new_crowd_input_path, notice: 'Your previous input was successfully added.' }
          format.json { render :show, status: :created, location: @crowd_input }
        else
          format.html {
            initialize_variables()
            render :new
          }
          format.json { render json: @crowd_input.errors, status: :unprocessable_entity }
        end
      end
    else
      render :text => "Anda telah diblokir"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crowd_input
      @crowd_input = CrowdInput.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def crowd_input_params
      params.require(:crowd_input).permit(:user_id, :tps_id, :prabowo_count, :jokowi_count, :broken_count, :problem)
    end

  def initialize_variables
    @my_progress = CrowdInput.where(:user_id => current_user.id).count()
    @global_progress = CrowdInput.count()
    # @count_prabowo = CrowdInput.sum(:prabowo_count)
    # @count_jokowi = CrowdInput.sum(:jokowi_count)
    # @count_broken = CrowdInput.sum(:broken_count)

    ac = CrowdInput.select("tps_id as tps_id, count(tps_id) as amount, min(prabowo_count) as pc, max(prabowo_count), min(jokowi_count) as jc, max(jokowi_count), min(broken_count) as bc, max(broken_count)").group(:tps_id).having("count(tps_id) > 1 and min(prabowo_count) = max(prabowo_count) and min(jokowi_count) = max(jokowi_count) and min(broken_count) = max(broken_count)")
    @count_prabowo = ac.to_a.sum{|a| a.pc}
    @count_jokowi = ac.to_a.sum{|a| a.jc}
    @count_broken = ac.to_a.sum{|a| a.bc}

    @top_contributors = CrowdInput.select("user_id as user_id, count(user_id) as amount").group(:user_id).order("amount DESC").limit(10)
    @banned_users = User.where(:is_banned => true)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if user_signed_in?
      redirect_to new_crowd_input_path
    end
    ac = CrowdInput.select("tps_id as tps_id, count(tps_id) as amount, min(prabowo_count) as pc, max(prabowo_count), min(jokowi_count) as jc, max(jokowi_count), min(broken_count) as bc, max(broken_count)").group(:tps_id).having("count(tps_id) > 1 and min(prabowo_count) = max(prabowo_count) and min(jokowi_count) = max(jokowi_count) and min(broken_count) = max(broken_count)")
    @count_prabowo = ac.to_a.sum{|a| a.pc}
    @count_jokowi = ac.to_a.sum{|a| a.jc}
    @count_broken = ac.to_a.sum{|a| a.bc}
    @global_progress = CrowdInput.count()

    @top_contributors = CrowdInput.select("user_id as user_id, count(user_id) as amount").group(:user_id).order("amount DESC").limit(10)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = User.find_by_id(params[:id])
  end
end

app/controllers/tps_controller.rb
class TpsController < ApplicationController
  before_action :set_tp, only: [:show, :edit, :update, :destroy]

  # GET /tps
  # GET /tps.json
  def index
    @tps = Tps.all
  end

  # GET /tps/1
  # GET /tps/1.json
  def show
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crowd_inputs_helper.rb
module CrowdInputsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/tps_helper.rb
module TpsHelper
end

app/views/crowd_inputs/_form.html.haml
:javascript
  $(function(){
    $('.to-add').change(function() {
      var total = 0;

      $('.to-add').each(function () {
        total += parseInt($(this).val());
      });

      $('#total').val(total);
    });
    $('#total').val(0);
  })

.row
  .col-md-3
    Share:
    .addthis_sharing_toolbox
    %b Jika didapati isian ngasal, account kamu akan diblock & semua entry kamu akan dihapus

    = form_for @crowd_input do |f|
      - if @crowd_input.errors.any?
        #error_explanation
          %h4= "#{pluralize(@crowd_input.errors.count, "error")} prohibited this crowd_input from being saved:"
          %ul
            - @crowd_input.errors.full_messages.each do |msg|
              %li= msg
      .form-group
        = f.hidden_field :tps_id
      .form-group
        = f.label :Prabowo
        = f.number_field :prabowo_count, :class => 'form-control to-add', :autofocus =>''
      .form-group
        = f.label :Jokowi
        = f.number_field :jokowi_count, :class => 'form-control to-add'
      .form-group
        = f.label :Total
        = number_field :total, 0, :id =>'total', :class => 'form-control', :disabled => ''
      .form-group
        = f.label 'Tidak sah'
        = f.number_field :broken_count, :class => 'form-control'
      .form-group
        = f.label :problem
        = f.text_area :problem, :class => 'form-control'
      .actions
        = f.submit 'Save', :class => 'btn btn-primary'
        = link_to "Lihat hasil", crowd_inputs_path, :class => 'btn btn-default'

    %h4 Blocked users
    %table.table.table-striped
      -@banned_users.each do |u|
        %tr
          %td= u.name
  .col-md-7
    = image_tag @crowd_input.c1_url, size:"600x800"
  .col-md-2
    %table.table.table-striped
      %tr
        %td Isian saya:
        %td
          = @my_progress
          forms
      %tr
        %td Total terisi:
        %td
          = @global_progress
          forms

      %tr
        %td Prabowo:
        %td= @count_prabowo
      %tr
        %td Jokowi:
        %td= @count_jokowi
      %tr
        %td Rusak:
        %td= @count_broken

    %h4 Top Contributors
    %table.table.table-striped
      -@top_contributors.each do |tc|
        %tr
          %td= tc.user.name
          %td= tc.amount

app/views/crowd_inputs/index.html.haml
.row
  .col-md-12
    = will_paginate @crowd_inputs
.row
  .col-md-12
    %table.table.table-striped
      %tr
        %th User
        %th Tps
        %th Prabowo
        %th Jokowi
        %th Broken
        %th Problem

      - @crowd_inputs.each do |crowd_input|
        %tr
          %td= crowd_input.user.name
          %td= link_to crowd_input.tps_id, crowd_input.c1_url
          %td= crowd_input.prabowo_count
          %td= crowd_input.jokowi_count
          %td= crowd_input.broken_count
          %td= crowd_input.problem

    %br

    = link_to 'New input', new_crowd_input_path, "class" => 'btn btn-primary'

app/views/crowd_inputs/new.html.haml
= render 'form'

app/views/layouts/application.html.haml
!!!
%html{lang: "en"}
  %head
    %meta{charset: "utf-8"}/
    %meta{content: "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{content: "width=device-width, initial-scale=1", name: "viewport"}/
    %meta{content: "Crowdsourcing Realcount Formulir C1 Pilpres 2014", name: "description"}/
    %meta{content: "", name: "author"}/
    %meta{content: "Crowdsourcing Realcount Pilpres 2014", property: "og:title"}/
    %meta{content: "Crowdsourcing Realcount Pilpres 2014", property: "og:site_name"}/
    %meta{content: "Crowdsourcing Realcount Formulir C1 Pilpres 2014", property: "og:description"}/

    %title Realcount Pilpres 2014
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

    %script{src: "//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-53bbbc685826fb13", type: "text/javascript"}
    = yield :header
  %body
    / Static navbar
    .navbar.navbar-default.navbar-static-top{role: "navigation"}
      .container
        .navbar-header
          %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          =link_to("Home", root_path, 'class' => 'navbar-brand')
        .navbar-collapse.collapse
          %ul.nav.navbar-nav.navbar-right
            %li
              %a{href: "#about"} About
            -if signed_in?
              %li
                =link_to("Sign out", destroy_user_session_path, method: :delete)
            -else
              %li
                =link_to("Log in", new_user_session_path)
        -#.nav-collapse
    .container
      -if notice
        .alert.alert-info= notice
      -if alert
        .alert.alert-danger= alert

      .alert.alert-info
        Saat ini ada update sistem untuk membersihkan entry yang ngasal. Dan juga implementasi sistem validasi otomatis.
        Counter expected akan berubah2 selama proses ini.
      = yield

    :javascript
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-52771154-1', 'auto');
      ga('send', 'pageview');

app/views/pages/home.html.haml
.row
  .col-md-9
    Share:
    .addthis_sharing_toolbox
    %h4 Data sementara
    %table.table.table-striped
      %tr
        %td TPS terdata
        %td= @global_progress
      %tr
        %td Prabowo
        %td= @count_prabowo
      %tr
        %td Jokowi
        %td= @count_jokowi
      %tr
        %td Tidak sah
        %td= @count_broken

    %h4 Top Contributors
    %table.table.table-striped
      -@top_contributors.each do |tc|
        %tr
          %td= tc.user.name
          %td= tc.amount
  .col-md-3
    - unless signed_in?
      =render "devise/sessions/new"

app/views/profiles/show.html.haml
.row
  .col-sm-12
    %h3
      User Profile
.row
  .col-sm-2
    #profile_picture
  .col-sm-4
    .col-sm-4 Name
    .col-sm-8= @user.name

    .col-sm-4 Email
    .col-sm-8= @user.email

-if @user.provider == 'facebook'
  :javascript
    window.fbAsyncInit = function() {
      FB.init({
        appId      : "#{ENV['FACEBOOK_APP_ID']}",
        xfbml      : true,
        version    : 'v2.0'
      });
      FB.api("/#{@user.uid}/picture?type=large",
        function (response) {
          if (response && !response.error) {
            console.log(response.data.url);
            $("#profile_picture").html("<img src='" + response.data.url + "' style: 'width:100%'/>");
          }
        }
      );
    };
    (function(d, s, id){
       var js, fjs = d.getElementsByTagName(s)[0];
       if (d.getElementById(id)) {return;}
       js = d.createElement(s); js.id = id;
       js.src = "//connect.facebook.net/en_US/sdk.js";
       fjs.parentNode.insertBefore(js, fjs);
     }(document, 'script', 'facebook-jssdk'));
-else
  :javascript
    $("#profile_picture").html("<img src='#{asset_path('person.png')}' style='width:100%'/>");

app/views/tps/index.html.haml
%h1 Listing tps

%table
  %tr
    %th Desa
    %th Kelurahan
    %th Tps
    %th
    %th
    %th

  - @tps.each do |tp|
    %tr
      %td= tp.desa
      %td= tp.kelurahan_id
      %td= tp.tps_id
      %td= link_to tp.c1_url, tp.c1_url

app/views/tps/show.html.haml
%p#notice= notice

%p
  %b Desa:
  = @tp.desa
%p
  %b Kelurahan:
  = @tp.kelurahan_id
%p
  %b Tps:
  = @tp.tps_id

= link_to 'Edit', edit_tp_path(@tp)
\|
= link_to 'Back', tps_index_path